Palusznium Rush: CSimulator.cpp File Reference
CSimulator.cpp File Reference
#include "CSimulator.h"
#include "CEconomicModel.h"
#include <algorithm>
#include <cmath>
#include <cstddef>
#include <limits>
#include <span>
#include <utility>
#include <vector>
Namespaces
namespace mass_balance
Functions
double circuit_performance (std::span< const int > const circuit_span)
Required GA-facing mass-balance performance function.
double circuit_performance (const ESE::Graph &graph)
Temporary graph overload retained for existing scaffold/tests.
Function Documentation
circuit_performance() [1/2]
double circuit_performance (const ESE::Graph & graph)
Temporary graph overload retained for existing scaffold/tests.
Parameters
graph ESE graph representation.
Returns
Placeholder performance until the graph-to-vector path is finalised.
Definition at line 479 of file CSimulator.cpp.
circuit_performance() [2/2]
double circuit_performance (std::span< const int > circuit_span)
Required GA-facing mass-balance performance function.
Parameters
circuit_span Full encoded circuit vector.
Returns
Economic value in pounds per second, or a large negative penalty for malformed/non-convergent circuits.
Definition at line 473 of file CSimulator.cpp.
References CSimulator::EvaluatePerformance().
Referenced by cli::EvaluateExecutor::Execute(), and cli::OptimiseExecutor::Execute().