Palusznium Rush: CSimulator.h File Reference
CSimulator.h File Reference
Mass-balance and economic-performance simulator for encoded circuits.
#include <span>
#include <string>
#include <vector>
#include "ESEGraph.h"
#include "GATypedefs.h"
Classes
struct mass_balance::SStream
Component mass-flow vector for one process stream.
struct mass_balance::SProductStreams
Final outlet streams from a circuit simulation.
struct mass_balance::SSimulationOptions
Numerical settings for the fixed-point mass-balance solver.
struct mass_balance::SSimulationResult
Diagnostic result returned by CSimulator::Simulate(...).
class CSimulator
Circuit mass-balance simulator.
Namespaces
namespace mass_balance
Functions
double circuit_performance (std::span< const int > circuit_span)
Required GA-facing mass-balance performance function.
double circuit_performance (const ESE::Graph &graph)
Temporary graph overload retained for existing scaffold/tests.
bool check_validity (std::span< const int > circuit_span)
Basic vector validity check.
bool check_validity (const ESE::Graph &graph)
Temporary graph validity overload retained for existing scaffold/tests.
Variables
constexpr int mass_balance::kComponentCount = 3
Number of solid components represented in every stream.
constexpr int mass_balance::kPalusznium = 0
Component index for palusznium.
constexpr int mass_balance::kGormanium = 1
Component index for gormanium.
constexpr int mass_balance::kWaste = 2
Component index for waste.
Detailed Description
Mass-balance and economic-performance simulator for encoded circuits.
Wiring contract for the rest of the project:
GATypedefs.h owns the circuit-vector encoding.
CSimulator owns mass-balance simulation, recycle convergence, stream routing, and economic scoring.
circuit_performance(std::span<const int>) is the GA-facing scalar fitness interface required by RequiredFunctions.h.
CSimulator::Simulate(...) is the richer diagnostic interface for testing, debugging, benchmarking, and presentation evidence.
The simulator deliberately uses the helper functions in GATypedefs.h instead of manually decoding vector offsets. This keeps vector-layout changes local to one header and avoids hidden wiring bugs.
Definition in file CSimulator.h.
Function Documentation
check_validity() [1/2]
bool check_validity (const ESE::Graph & graph)
Temporary graph validity overload retained for existing scaffold/tests.
Parameters
graph ESE graph representation.
Returns
true for now. Replace when graph validity is implemented.
Definition at line 162 of file CircuitValidity.cpp.
References graph_check_validity().
check_validity() [2/2]
bool check_validity (std::span< const int > circuit_span)
Basic vector validity check.
Parameters
circuit_span Full encoded circuit vector.
Returns
true if the vector is structurally well-formed.
Definition at line 157 of file CircuitValidity.cpp.
References vector_check_validity().
Referenced by cli::OptimiseExecutor::Execute(), cli::ValidateExecutor::Execute(), run_graph_validity_cases(), and run_vector_validity_cases().
circuit_performance() [1/2]
double circuit_performance (const ESE::Graph & graph)
Temporary graph overload retained for existing scaffold/tests.
Parameters
graph ESE graph representation.
Returns
Placeholder performance until the graph-to-vector path is finalised.
Definition at line 479 of file CSimulator.cpp.
circuit_performance() [2/2]
double circuit_performance (std::span< const int > circuit_span)
Required GA-facing mass-balance performance function.
Parameters
circuit_span Full encoded circuit vector.
Returns
Economic value in pounds per second, or a large negative penalty for malformed/non-convergent circuits.
Definition at line 473 of file CSimulator.cpp.
References CSimulator::EvaluatePerformance().
Referenced by cli::EvaluateExecutor::Execute(), and cli::OptimiseExecutor::Execute().