Palusznium Rush: CircuitValidity.cpp File Reference
CircuitValidity.cpp File Reference
#include "CircuitValidity.h"
#include <algorithm>
#include <functional>
#include <limits>
#include <set>
#include <utility>
#include <vector>
#include "CircuitVectorParser.h"
Functions
bool vector_check_validity (std::span< const int > circuit_span)
bool graph_check_validity (const ESE::Graph &graph)
bool check_validity (std::span< const int > circuit_span)
Basic vector validity check.
bool check_validity (const ESE::Graph &graph)
Temporary graph validity overload retained for existing scaffold/tests.
Function Documentation
check_validity() [1/2]
bool check_validity (const ESE::Graph & graph)
Temporary graph validity overload retained for existing scaffold/tests.
Parameters
graph ESE graph representation.
Returns
true for now. Replace when graph validity is implemented.
Definition at line 162 of file CircuitValidity.cpp.
References graph_check_validity().
check_validity() [2/2]
bool check_validity (std::span< const int > circuit_span)
Basic vector validity check.
Parameters
circuit_span Full encoded circuit vector.
Returns
true if the vector is structurally well-formed.
Definition at line 157 of file CircuitValidity.cpp.
References vector_check_validity().
Referenced by cli::OptimiseExecutor::Execute(), cli::ValidateExecutor::Execute(), run_graph_validity_cases(), and run_vector_validity_cases().
graph_check_validity()
bool graph_check_validity (const ESE::Graph & graph)
Definition at line 130 of file CircuitValidity.cpp.
Referenced by check_validity(), check_validity(), and run_graph_validity_cases().
vector_check_validity()
bool vector_check_validity (std::span< const int > circuit_span)
Definition at line 110 of file CircuitValidity.cpp.
References circuit_vector::parse_circuit_vector().
Referenced by check_validity(), and run_vector_validity_cases().