Palusznium Rush: GATypedefs.h File Reference
GATypedefs.h File Reference
#include <cstddef>
#include <limits>
#include <map>
#include <numeric>
#include <span>
#include <vector>
#include "GraphTypedefs.h"
Functions
int cv_num_feed (std::span< const int > circuit)
int cv_num_units (std::span< const int > circuit)
int cv_num_products (std::span< const int > circuit)
int cv_unit_type (std::span< const int > circuit, int i)
std::size_t cv_fixed_prefix_length (int n)
std::size_t cv_variable_start (std::span< const int > circuit)
std::size_t cv_variable_length (std::span< const int > circuit)
std::size_t cv_expected_length (std::span< const int > circuit)
int cv_feed_dest (std::span< const int > circuit)
int cv_tailings_dest (std::span< const int > circuit)
std::size_t cv_unit_dest_full_offset (std::span< const int > circuit, int unit_i)
int cv_unit_dest (std::span< const int > circuit, int unit_i, int output_i)
bool cv_is_unit_dest (std::span< const int > circuit, int dest)
bool cv_is_product_dest (std::span< const int > circuit, int dest)
bool cv_is_tailings_dest (std::span< const int > circuit, int dest)
bool cv_is_valid_dest (std::span< const int > circuit, int dest)
int cv_type_a_conc_output ()
int cv_type_a_tails_output ()
int cv_type_b_conc1_output ()
int cv_type_b_conc2_output ()
int cv_type_b_tails_output ()
int cv_tails_output_index (std::span< const int > circuit, int unit_i)
bool cv_has_valid_shape (std::span< const int > circuit)
Function Documentation
cv_expected_length()
std::size_t cv_expected_length (std::span< const int > circuit) inline
Definition at line 153 of file GATypedefs.h.
References cv_variable_length(), and cv_variable_start().
Referenced by cv_has_valid_shape().
cv_feed_dest()
int cv_feed_dest (std::span< const int > circuit) inline
Definition at line 161 of file GATypedefs.h.
References cv_variable_start().
Referenced by cv_has_valid_shape(), and CSimulator::Simulate().
cv_fixed_prefix_length()
std::size_t cv_fixed_prefix_length (int n) inline
Definition at line 131 of file GATypedefs.h.
Referenced by cv_has_valid_shape(), cv_variable_start(), default_crossover(), default_generator(), and default_mutator().
cv_has_valid_shape()
bool cv_has_valid_shape (std::span< const int > circuit) inline
Definition at line 267 of file GATypedefs.h.
References cv_expected_length(), cv_feed_dest(), cv_fixed_prefix_length(), cv_is_valid_dest(), cv_num_feed(), cv_num_products(), cv_num_units(), cv_unit_dest(), and cv_unit_type().
Referenced by CSimulator::Simulate().
cv_is_product_dest()
bool cv_is_product_dest (std::span< const int > circuit, int dest) inline
Definition at line 206 of file GATypedefs.h.
References cv_num_products(), and cv_num_units().
cv_is_tailings_dest()
bool cv_is_tailings_dest (std::span< const int > circuit, int dest) inline
Definition at line 214 of file GATypedefs.h.
References cv_tailings_dest().
cv_is_unit_dest()
bool cv_is_unit_dest (std::span< const int > circuit, int dest) inline
Definition at line 199 of file GATypedefs.h.
References cv_num_units().
cv_is_valid_dest()
bool cv_is_valid_dest (std::span< const int > circuit, int dest) inline
Definition at line 220 of file GATypedefs.h.
References cv_tailings_dest().
Referenced by cv_has_valid_shape().
cv_num_feed()
int cv_num_feed (std::span< const int > circuit) inline
Definition at line 104 of file GATypedefs.h.
Referenced by cv_has_valid_shape().
cv_num_products()
int cv_num_products (std::span< const int > circuit) inline
Definition at line 117 of file GATypedefs.h.
Referenced by cv_has_valid_shape(), cv_is_product_dest(), cv_tailings_dest(), default_generator(), and default_mutator().
cv_num_units()
int cv_num_units (std::span< const int > circuit) inline
Definition at line 110 of file GATypedefs.h.
Referenced by cv_has_valid_shape(), cv_is_product_dest(), cv_is_unit_dest(), cv_tailings_dest(), cv_variable_length(), cv_variable_start(), default_crossover(), default_generator(), default_mutator(), CEconomicModel::Evaluate(), and CSimulator::Simulate().
cv_tailings_dest()
int cv_tailings_dest (std::span< const int > circuit) inline
Definition at line 169 of file GATypedefs.h.
References cv_num_products(), and cv_num_units().
Referenced by cv_is_tailings_dest(), cv_is_valid_dest(), default_generator(), and default_mutator().
cv_tails_output_index()
int cv_tails_output_index (std::span< const int > circuit, int unit_i) inline
Definition at line 256 of file GATypedefs.h.
References cv_unit_type().
cv_type_a_conc_output()
int cv_type_a_conc_output () inline
Definition at line 230 of file GATypedefs.h.
cv_type_a_tails_output()
int cv_type_a_tails_output () inline
Definition at line 234 of file GATypedefs.h.
cv_type_b_conc1_output()
int cv_type_b_conc1_output () inline
Definition at line 240 of file GATypedefs.h.
cv_type_b_conc2_output()
int cv_type_b_conc2_output () inline
Definition at line 244 of file GATypedefs.h.
cv_type_b_tails_output()
int cv_type_b_tails_output () inline
Definition at line 248 of file GATypedefs.h.
cv_unit_dest()
int cv_unit_dest (std::span< const int > circuit, int unit_i, int output_i) inline
Definition at line 189 of file GATypedefs.h.
References cv_unit_dest_full_offset().
Referenced by cv_has_valid_shape(), and CSimulator::Simulate().
cv_unit_dest_full_offset()
std::size_t cv_unit_dest_full_offset (std::span< const int > circuit, int unit_i) inline
Definition at line 177 of file GATypedefs.h.
References cv_unit_type(), and cv_variable_start().
Referenced by cv_unit_dest().
cv_unit_type()
int cv_unit_type (std::span< const int > circuit, int i) inline
Definition at line 123 of file GATypedefs.h.
Referenced by cv_has_valid_shape(), cv_tails_output_index(), cv_unit_dest_full_offset(), cv_variable_length(), default_generator(), CEconomicModel::Evaluate(), and CSimulator::Simulate().
cv_variable_length()
std::size_t cv_variable_length (std::span< const int > circuit) inline
Definition at line 143 of file GATypedefs.h.
References cv_num_units(), and cv_unit_type().
Referenced by cv_expected_length(), default_crossover(), default_generator(), default_mutator(), and cli::OptimiseExecutor::Execute().
cv_variable_start()
std::size_t cv_variable_start (std::span< const int > circuit) inline
Definition at line 137 of file GATypedefs.h.
References cv_fixed_prefix_length(), and cv_num_units().
Referenced by cv_expected_length(), cv_feed_dest(), and cv_unit_dest_full_offset().