Palusznium Rush: Genetic_Algorithm.h File Reference
Genetic_Algorithm.h File Reference
#include <span>
#include <vector>
#include "CSRGraph.h"
#include "RequiredFunctions.h"
Classes
struct Algorithm_Parameters
Functions
BaseResult< std::span< int > > optimize_span (std::span< const int > fixed_prefix, const FitnessFunction &performance_function, const ValidityFunction &validity_checker, GA_Functions ga_functions, Algorithm_Parameters algorithm_parameters)
BaseResult< std::span< int > > optimize_swappable_span (int num_units, const FitnessFunction &performance_function, const ValidityFunction &validity_checker, GA_Functions ga_functions, Algorithm_Parameters algorithm_parameters)
bool default_validity_checker (std::span< const int > values)
void unit_block_crossover (std::span< const int > fixed_prefix, std::span< const int > parent1_values, std::span< const int > parent2_values, std::span< std::span< int > > child_values, RandomNumberGenerator &rng)
std::vector< int > make_full_vector (std::span< const int > fixed_prefix, std::span< const int > variable_values)
Variables
Algorithm_Parameters default_ga_parameters
Function Documentation
default_validity_checker()
bool default_validity_checker (std::span< const int > values)
Definition at line 1380 of file Genetic_Algorithm.cpp.
make_full_vector()
std::vector< int > make_full_vector (std::span< const int > fixed_prefix, std::span< const int > variable_values)
Definition at line 23 of file Genetic_Algorithm.cpp.
Referenced by optimize_span().
optimize_span()
BaseResult< std::span< int > > optimize_span (std::span< const int > fixed_prefix, const FitnessFunction & performance_function, const ValidityFunction & validity_checker, GA_Functions ga_functions, Algorithm_Parameters algorithm_parameters)
Evaluate a batch of candidates while keeping cache access serial.
The evaluation cache is a shared std::map, so it is checked and updated outside the OpenMP region. Only cache misses are sent to the parallel helper, where each thread updates a different candidate entry.
Definition at line 825 of file Genetic_Algorithm.cpp.
References Algorithm_Parameters::duplicate_attempt_multiplier, Algorithm_Parameters::elitism_count, Algorithm_Parameters::improvement_epsilon, Algorithm_Parameters::initial_attempt_multiplier, make_full_vector(), Algorithm_Parameters::max_iterations, Algorithm_Parameters::max_stagnation, Algorithm_Parameters::offspring_attempt_multiplier, Algorithm_Parameters::population_size, Algorithm_Parameters::tournament_size, GA_Functions::vector_extent, and GA_Functions::vector_generator.
Referenced by cli::OptimiseExecutor::Execute(), and optimize_span().
optimize_swappable_span()
BaseResult< std::span< int > > optimize_swappable_span (int num_units, const FitnessFunction & performance_function, const ValidityFunction & validity_checker, GA_Functions ga_functions, Algorithm_Parameters algorithm_parameters)
Definition at line 1132 of file Genetic_Algorithm.cpp.
References Algorithm_Parameters::duplicate_attempt_multiplier, Algorithm_Parameters::elitism_count, Algorithm_Parameters::improvement_epsilon, Algorithm_Parameters::initial_attempt_multiplier, Algorithm_Parameters::max_iterations, Algorithm_Parameters::max_stagnation, Algorithm_Parameters::offspring_attempt_multiplier, Algorithm_Parameters::population_size, Algorithm_Parameters::swappable_similarity_threshold, and Algorithm_Parameters::tournament_size.
Referenced by cli::OptimiseExecutor::Execute().
unit_block_crossover()
void unit_block_crossover (std::span< const int > fixed_prefix, std::span< const int > parent1_values, std::span< const int > parent2_values, std::span< std::span< int > > child_values, RandomNumberGenerator & rng)
Definition at line 1654 of file Genetic_Algorithm.cpp.
References RandomNumberGenerator::rand().
Referenced by cli::OptimiseExecutor::Execute().
Variable Documentation
default_ga_parameters
Algorithm_Parameters default_ga_parameters extern
Definition at line 18 of file Genetic_Algorithm.cpp.
Referenced by optimize_span().