Palusznium Rush: Genetic_Algorithm.cpp File Reference
Genetic_Algorithm.cpp File Reference
#include <algorithm>
#include <cstddef>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <limits>
#include <map>
#include <optional>
#include <random>
#include <utility>
#include <vector>
#include "CSRGraph.h"
#include "Genetic_Algorithm.h"
#include "GraphTypedefs.h"
#include "PRNG.h"
Functions
std::vector< int > make_full_vector (std::span< const int > fixed_prefix, std::span< const int > variable_values)
BaseResult< std::span< int > > optimize_span (std::span< const int > const fixed_prefix, const FitnessFunction &performance_function, const ValidityFunction &validity_checker, GA_Functions ga_functions, Algorithm_Parameters algorithm_parameters)
BaseResult< std::span< int > > optimize_swappable_span (int num_units, const FitnessFunction &performance_function, const ValidityFunction &validity_checker, GA_Functions ga_functions, Algorithm_Parameters algorithm_parameters)
BaseResult< std::span< int > > optimize_span (std::span< const int > const fixed_prefix, const FitnessFunction &performance_function, const ValidityFunction &validity_checker, GA_Functions ga_functions)
bool default_validity_checker (std::span< const int > const values)
void default_generator (std::span< const int > const fixed_prefix, std::span< int > values, RandomNumberGenerator &rng)
void default_mutator (std::span< const int > const fixed_prefix, std::span< int > values, std::size_t max_mutations, RandomNumberGenerator &rng)
void default_crossover (std::span< const int > const fixed_prefix, std::span< const int > const parent1_values, std::span< const int > const parent2_values, std::span< std::span< int > > child_values, RandomNumberGenerator &rng)
void unit_block_crossover (std::span< const int > const fixed_prefix, std::span< const int > const parent1_values, std::span< const int > const parent2_values, std::span< std::span< int > > child_values, RandomNumberGenerator &rng)
double default_similarity (std::span< const int > const fixed_prefix, std::span< const int > const vec1, std::span< const int > const vec2)
Variables
Algorithm_Parameters default_ga_parameters {}
Function Documentation
default_crossover()
void default_crossover (std::span< const int > const fixed_prefix, std::span< const int > const parent1_values, std::span< const int > const parent2_values, std::span< std::span< int > > child_values, RandomNumberGenerator & rng)
Definition at line 1570 of file Genetic_Algorithm.cpp.
References cv_fixed_prefix_length(), cv_num_units(), cv_variable_length(), and RandomNumberGenerator::rand().
default_generator()
void default_generator (std::span< const int > const fixed_prefix, std::span< int > values, RandomNumberGenerator & rng)
Definition at line 1388 of file Genetic_Algorithm.cpp.
References cv_fixed_prefix_length(), cv_num_products(), cv_num_units(), cv_tailings_dest(), cv_unit_type(), cv_variable_length(), and RandomNumberGenerator::rand().
default_mutator()
void default_mutator (std::span< const int > const fixed_prefix, std::span< int > values, std::size_t max_mutations, RandomNumberGenerator & rng)
Definition at line 1490 of file Genetic_Algorithm.cpp.
References cv_fixed_prefix_length(), cv_num_products(), cv_num_units(), cv_tailings_dest(), cv_variable_length(), and RandomNumberGenerator::rand().
default_similarity()
double default_similarity (std::span< const int > const fixed_prefix, std::span< const int > const vec1, std::span< const int > const vec2)
Definition at line 1706 of file Genetic_Algorithm.cpp.
default_validity_checker()
bool default_validity_checker (std::span< const int > const values)
Definition at line 1380 of file Genetic_Algorithm.cpp.
make_full_vector()
std::vector< int > make_full_vector (std::span< const int > fixed_prefix, std::span< const int > variable_values)
Definition at line 23 of file Genetic_Algorithm.cpp.
Referenced by optimize_span().
optimize_span() [1/2]
BaseResult< std::span< int > > optimize_span (std::span< const int > const fixed_prefix, const FitnessFunction & performance_function, const ValidityFunction & validity_checker, GA_Functions ga_functions)
Definition at line 1371 of file Genetic_Algorithm.cpp.
References default_ga_parameters, and optimize_span().
optimize_span() [2/2]
BaseResult< std::span< int > > optimize_span (std::span< const int > const fixed_prefix, const FitnessFunction & performance_function, const ValidityFunction & validity_checker, GA_Functions ga_functions, Algorithm_Parameters algorithm_parameters)
Evaluate a batch of candidates while keeping cache access serial.
The evaluation cache is a shared std::map, so it is checked and updated outside the OpenMP region. Only cache misses are sent to the parallel helper, where each thread updates a different candidate entry.
Definition at line 825 of file Genetic_Algorithm.cpp.
References Algorithm_Parameters::duplicate_attempt_multiplier, Algorithm_Parameters::elitism_count, Algorithm_Parameters::improvement_epsilon, Algorithm_Parameters::initial_attempt_multiplier, make_full_vector(), Algorithm_Parameters::max_iterations, Algorithm_Parameters::max_stagnation, Algorithm_Parameters::offspring_attempt_multiplier, Algorithm_Parameters::population_size, Algorithm_Parameters::tournament_size, GA_Functions::vector_extent, and GA_Functions::vector_generator.
Referenced by cli::OptimiseExecutor::Execute(), and optimize_span().
optimize_swappable_span()
BaseResult< std::span< int > > optimize_swappable_span (int num_units, const FitnessFunction & performance_function, const ValidityFunction & validity_checker, GA_Functions ga_functions, Algorithm_Parameters algorithm_parameters)
Definition at line 1132 of file Genetic_Algorithm.cpp.
References Algorithm_Parameters::duplicate_attempt_multiplier, Algorithm_Parameters::elitism_count, Algorithm_Parameters::improvement_epsilon, Algorithm_Parameters::initial_attempt_multiplier, Algorithm_Parameters::max_iterations, Algorithm_Parameters::max_stagnation, Algorithm_Parameters::offspring_attempt_multiplier, Algorithm_Parameters::population_size, Algorithm_Parameters::swappable_similarity_threshold, and Algorithm_Parameters::tournament_size.
Referenced by cli::OptimiseExecutor::Execute().
unit_block_crossover()
void unit_block_crossover (std::span< const int > const fixed_prefix, std::span< const int > const parent1_values, std::span< const int > const parent2_values, std::span< std::span< int > > child_values, RandomNumberGenerator & rng)
Definition at line 1654 of file Genetic_Algorithm.cpp.
References RandomNumberGenerator::rand().
Referenced by cli::OptimiseExecutor::Execute().
Variable Documentation
default_ga_parameters
Algorithm_Parameters default_ga_parameters {}
Definition at line 18 of file Genetic_Algorithm.cpp.
Referenced by optimize_span().