Palusznium Rush: RequiredFunctions.h File Reference
RequiredFunctions.h File Reference
#include <cstddef>
#include <functional>
#include <random>
#include <span>
#include "CircuitValidity.h"
#include "ESEGraph.h"
#include "GATypedefs.h"
Classes
class RandomNumberGenerator
struct GA_Functions
struct BaseResult< T >
struct BaseResult< std::span< int > >
Typedefs
using FitnessFunction = std::function<double(std::span<const int>)>
Callable type used by the GA to evaluate circuit fitness.
using ValidityFunction = std::function<bool(std::span<const int>)>
Callable type used by the GA to check circuit validity.
Functions
void seed_rngs (unsigned seed)
void default_generator (std::span< const int > fixed_prefix, std::span< int > values, RandomNumberGenerator &rng)
void default_mutator (std::span< const int > fixed_prefix, std::span< int > values, std::size_t max_mutations, RandomNumberGenerator &rng)
void default_crossover (std::span< const int > fixed_prefix, std::span< const int > parent1_values, std::span< const int > parent2_values, std::span< std::span< int > > child_values, RandomNumberGenerator &rng)
double default_similarity (std::span< const int > fixed_prefix, std::span< const int > vec1, std::span< const int > vec2)
BaseResult< std::span< int > > optimize_span (std::span< const int > fixed_prefix, const FitnessFunction &performance_function, const ValidityFunction &validity_checker, GA_Functions ga_functions)
double circuit_performance (std::span< const int > circuit_span)
Required GA-facing mass-balance performance function.
double circuit_performance (const ESE::Graph &graph)
Temporary graph overload retained for existing scaffold/tests.
bool check_validity (std::span< const int > circuit_span)
Validates a circuit vector (overload for flat integer span).
bool check_validity (const ESE::Graph &graph)
Validates a circuit graph (overload for ESE::Graph).
void generate_circuit_vector (std::span< const int > fixed_values, std::span< int > random_values, RandomNumberGenerator &rng)
void mutate_circuitvector (std::span< const int > fixed_values, std::span< int > mutable_values, RandomNumberGenerator &rng)
void crossover_circuit_vectors (std::span< const int > fixed_values, std::span< const int > parent1_values, std::span< const int > parent2_values, std::span< std::span< int > > child_values, RandomNumberGenerator &rng)
void plot_span (std::span< const int > values, const char *filename)
Writes a circuit-vector diagram to filename.
void plot_graph (const ESE::Graph &graph, const char *filename)
Writes a ESE::Graph diagram to filename.
Typedef Documentation
FitnessFunction
using FitnessFunction = std::function<double(std::span<const int>)>
Callable type used by the GA to evaluate circuit fitness.
This is a std::function rather than a raw function pointer so CLI optimise mode can pass a simulator configured with economic/feed overrides.
Definition at line 85 of file RequiredFunctions.h.
ValidityFunction
using ValidityFunction = std::function<bool(std::span<const int>)>
Callable type used by the GA to check circuit validity.
Definition at line 90 of file RequiredFunctions.h.
Function Documentation
check_validity() [1/2]
bool check_validity (const ESE::Graph & graph)
Validates a circuit graph (overload for ESE::Graph).
Check whether an ESEGraph circuit representation is structurally valid.
Convenience overload dispatching to graph_check_validity().
Parameters
graph The graph representation of the circuit to validate.
Returns
true if valid, false otherwise.
Validates a circuit graph (overload for ESE::Graph).
Parameters
graph ESE graph representation.
Returns
true if the graph passes the same topology checks as the vector-based validity checker; false otherwise.
Definition at line 237 of file CircuitValidity.cpp.
check_validity() [2/2]
bool check_validity (std::span< const int > circuit_span)
Validates a circuit vector (overload for flat integer span).
Check whether an encoded circuit vector is structurally valid.
Convenience overload dispatching to vector_check_validity().
Parameters
circuit_span The flat integer circuit vector to validate.
Returns
true if valid, false otherwise.
Validates a circuit vector (overload for flat integer span).
Parameters
circuit_span Full encoded circuit vector.
Returns
true if the vector is structurally well-formed.
Definition at line 223 of file CircuitValidity.cpp.
circuit_performance() [1/2]
double circuit_performance (const ESE::Graph & graph)
Temporary graph overload retained for existing scaffold/tests.
Parameters
graph ESE graph representation.
Returns
Placeholder performance until the graph-to-vector path is finalised.
Definition at line 469 of file CSimulator.cpp.
circuit_performance() [2/2]
double circuit_performance (std::span< const int > circuit_span)
Required GA-facing mass-balance performance function.
Parameters
circuit_span Full encoded circuit vector.
Returns
Economic value in pounds per second, or a large negative penalty for malformed/non-convergent circuits.
Definition at line 463 of file CSimulator.cpp.
Referenced by circuit_performance().
crossover_circuit_vectors()
void crossover_circuit_vectors (std::span< const int > fixed_values, std::span< const int > parent1_values, std::span< const int > parent2_values, std::span< std::span< int > > child_values, RandomNumberGenerator & rng)
default_crossover()
void default_crossover (std::span< const int > fixed_prefix, std::span< const int > parent1_values, std::span< const int > parent2_values, std::span< std::span< int > > child_values, RandomNumberGenerator & rng)
Definition at line 1570 of file Genetic_Algorithm.cpp.
References cv_fixed_prefix_length(), cv_num_units(), cv_variable_length(), and RandomNumberGenerator::rand().
default_generator()
void default_generator (std::span< const int > fixed_prefix, std::span< int > values, RandomNumberGenerator & rng)
Definition at line 1388 of file Genetic_Algorithm.cpp.
References cv_fixed_prefix_length(), cv_num_products(), cv_num_units(), cv_tailings_dest(), cv_unit_type(), cv_variable_length(), and RandomNumberGenerator::rand().
default_mutator()
void default_mutator (std::span< const int > fixed_prefix, std::span< int > values, std::size_t max_mutations, RandomNumberGenerator & rng)
Definition at line 1490 of file Genetic_Algorithm.cpp.
References cv_fixed_prefix_length(), cv_num_products(), cv_num_units(), cv_tailings_dest(), cv_variable_length(), and RandomNumberGenerator::rand().
default_similarity()
double default_similarity (std::span< const int > fixed_prefix, std::span< const int > vec1, std::span< const int > vec2)
Definition at line 1706 of file Genetic_Algorithm.cpp.
generate_circuit_vector()
void generate_circuit_vector (std::span< const int > fixed_values, std::span< int > random_values, RandomNumberGenerator & rng)
mutate_circuitvector()
void mutate_circuitvector (std::span< const int > fixed_values, std::span< int > mutable_values, RandomNumberGenerator & rng)
optimize_span()
BaseResult< std::span< int > > optimize_span (std::span< const int > fixed_prefix, const FitnessFunction & performance_function, const ValidityFunction & validity_checker, GA_Functions ga_functions)
Definition at line 1371 of file Genetic_Algorithm.cpp.
References default_ga_parameters, and optimize_span().
plot_graph()
void plot_graph (const ESE::Graph & graph, const char * filename)
Writes a ESE::Graph diagram to filename.
Generates DOT source via visualization::build_graph_dot() and persists it using write_or_render(), which will request Graphviz to produce an image when the extension is recognised.
Parameters
graph Graph to visualise.
filename Destination file path (nullptr is a no-op).
Definition at line 428 of file Visualization.cpp.
References visualization::build_graph_dot().
plot_span()
void plot_span (std::span< const int > values, const char * filename)
Writes a circuit-vector diagram to filename.
Generates DOT source via visualization::build_circuit_dot() and persists it using write_or_render(), which will request Graphviz to produce an image when the extension is recognised.
Parameters
values The flat integer circuit vector to visualise.
filename Destination file path (nullptr is a no-op).
Definition at line 413 of file Visualization.cpp.
References visualization::build_circuit_dot().
Referenced by cli::OptimiseExecutor::Execute().
seed_rngs()
void seed_rngs (unsigned seed)
Improved PRNG using mt19937 (Mersenne Twister Algorithm) with one generator per OpenMP thread, using the provided fast_random1 approach.
This approach is an improvement from the old LCG framework, as it covers a much larger period, is thread safe, and is made compatible with the existing RNG usage.
Definition at line 24 of file PRNG.cpp.