Palusznium Rush: Simulated_Annealing.cpp File Reference
Simulated_Annealing.cpp File Reference
#include <algorithm>
#include <cmath>
#include <limits>
#include <map>
#include <utility>
#include <vector>
#include "GATypedefs.h"
#include "Genetic_Algorithm.h"
#include "PRNG.h"
#include "Simulated_Annealing.h"
Functions
BaseResult< std::span< int > > optimize_span_sa (std::span< const int > const fixed_prefix, const FitnessFunction &performance_function, const ValidityFunction &validity_checker, GA_Functions ga_functions, SA_Parameters sa_parameters)
Run simulated annealing over the variable part of a circuit vector.
BaseResult< std::span< int > > optimize_span_sa (std::span< const int > const fixed_prefix, const FitnessFunction &performance_function, const ValidityFunction &validity_checker, GA_Functions ga_functions)
Convenience overload that uses default_sa_parameters.
BaseResult< std::span< int > > optimize_swappable_span_sa (int num_units, const FitnessFunction &performance_function, const ValidityFunction &validity_checker, GA_Functions ga_functions, SA_Parameters sa_parameters)
Run simulated annealing over both unit types and wiring.
BaseResult< std::span< int > > optimize_swappable_span_sa (int num_units, const FitnessFunction &performance_function, const ValidityFunction &validity_checker, GA_Functions ga_functions)
Convenience overload that uses default_sa_parameters.
Variables
SA_Parameters default_sa_parameters {}
Project-wide default values for SA_Parameters.
Function Documentation
optimize_span_sa() [1/2]
BaseResult< std::span< int > > optimize_span_sa (std::span< const int > fixed_prefix, const FitnessFunction & performance_function, const ValidityFunction & validity_checker, GA_Functions ga_functions)
Convenience overload that uses default_sa_parameters.
Equivalent to invoking the five-argument overload with the project default tuning. Parameters are documented on the primary overload.
Definition at line 263 of file Simulated_Annealing.cpp.
References default_sa_parameters, and optimize_span_sa().
optimize_span_sa() [2/2]
BaseResult< std::span< int > > optimize_span_sa (std::span< const int > fixed_prefix, const FitnessFunction & performance_function, const ValidityFunction & validity_checker, GA_Functions ga_functions, SA_Parameters sa_parameters)
Run simulated annealing over the variable part of a circuit vector.
Mirrors the contract of optimize_span. Returns the best valid circuit encountered during the annealing trajectory, evaluated against the supplied fitness function. On total failure to seed any valid initial state the returned vector is a marker whose unit count is set to a negative value and whose performance is negative infinity.
Memory ownership of the returned data follows the BaseResult convention and is released by the destructor of the returned object.
Parameters
fixed_prefix Fixed circuit-vector prefix that determines the shape of the search space.
performance_function Scalar fitness function evaluated on full circuit vectors. Required only to be defined on validity-passing inputs.
validity_checker Predicate used to reject ill-formed neighbours.
ga_functions Generator, mutator, and extent callbacks that define the variable-part search space. The crossover and similarity entries are ignored.
sa_parameters Annealing schedule and termination parameters.
Returns
The best circuit vector found together with its fitness, or the failure marker described above.
Definition at line 150 of file Simulated_Annealing.cpp.
References SA_Parameters::cooling_rate, SA_Parameters::final_temperature, SA_Parameters::improvement_epsilon, SA_Parameters::initial_attempt_multiplier, SA_Parameters::initial_temperature, SA_Parameters::iterations_per_temperature, SA_Parameters::max_iterations, SA_Parameters::max_mutations, SA_Parameters::max_stagnation, DefaultRandomNumberGenerator::random(), SA_Parameters::restart_count, GA_Functions::vector_extent, and GA_Functions::vector_mutator.
Referenced by cli::OptimiseExecutor::Execute(), and optimize_span_sa().
optimize_swappable_span_sa() [1/2]
BaseResult< std::span< int > > optimize_swappable_span_sa (int num_units, const FitnessFunction & performance_function, const ValidityFunction & validity_checker, GA_Functions ga_functions)
Convenience overload that uses default_sa_parameters.
Equivalent to invoking the five-argument overload with the project default tuning. Parameters are documented on the primary overload.
Definition at line 405 of file Simulated_Annealing.cpp.
References default_sa_parameters, and optimize_swappable_span_sa().
optimize_swappable_span_sa() [2/2]
BaseResult< std::span< int > > optimize_swappable_span_sa (int num_units, const FitnessFunction & performance_function, const ValidityFunction & validity_checker, GA_Functions ga_functions, SA_Parameters sa_parameters)
Run simulated annealing over both unit types and wiring.
Counterpart to optimize_swappable_span. Each unit's type is selected from {Type A, Type B} and may be mutated during the trajectory according to SA_Parameters::type_mutation_probability. When a type is flipped a fresh wiring vector is generated for the new prefix, since the variable-part length depends on the unit-type sequence. otherwise the wiring is mutated in place via GA_Functions::vector_mutator.
Memory ownership of the returned data follows the BaseResult convention and is released by the destructor of the returned object.
Parameters
num_units Number of separation units in the circuit. Must be positive. non-positive values produce a failure marker without invoking the annealer.
performance_function Scalar fitness function evaluated on full circuit vectors.
validity_checker Predicate used to reject ill-formed neighbours.
ga_functions Generator, mutator, and extent callbacks that define the variable-part search space.
sa_parameters Annealing schedule and termination parameters, including SA_Parameters::type_mutation_probability.
Returns
The best circuit vector found together with its fitness, or a failure marker of the form [1, -1, 3] with performance set to negative infinity.
Definition at line 272 of file Simulated_Annealing.cpp.
References SA_Parameters::cooling_rate, SA_Parameters::final_temperature, SA_Parameters::improvement_epsilon, SA_Parameters::initial_attempt_multiplier, SA_Parameters::initial_temperature, SA_Parameters::iterations_per_temperature, SA_Parameters::max_iterations, SA_Parameters::max_mutations, SA_Parameters::max_stagnation, DefaultRandomNumberGenerator::rand(), DefaultRandomNumberGenerator::random(), SA_Parameters::restart_count, SA_Parameters::type_mutation_probability, GA_Functions::vector_extent, GA_Functions::vector_generator, and GA_Functions::vector_mutator.
Referenced by cli::OptimiseExecutor::Execute(), and optimize_swappable_span_sa().
Variable Documentation
default_sa_parameters
SA_Parameters default_sa_parameters {}
Project-wide default values for SA_Parameters.
Defined in the implementation translation unit. CLI front ends should copy this and selectively override fields rather than constructing a fresh SA_Parameters in place, so that future default tuning changes propagate automatically.
Definition at line 13 of file Simulated_Annealing.cpp.
Referenced by optimize_span_sa(), and optimize_swappable_span_sa().