Palusznium Rush: Visualization.cpp File Reference
Visualization.cpp File Reference
#include "Visualization.h"
#include <algorithm>
#include <cctype>
#include <cstdio>
#include <fstream>
#include <iomanip>
#include <span>
#include <sstream>
#include <string>
#include "CSRGraph.h"
#include "CSimulator.h"
#include "CircuitVectorParser.h"
#include "RequiredFunctions.h"
Namespaces
namespace visualization
Functions
std::string visualization::graphviz_output_format (const char *filename)
Returns the Graphviz output format string provided by filename's extension.
std::string visualization::build_circuit_dot (std::span< const int > circuit_vector)
Builds a Graphviz dot representation of a circuit vector.
std::string visualization::build_circuit_dot (std::span< const int > circuit_vector, const mass_balance::SSimulationResult &result)
Builds an annotated Graphviz dot representation of a circuit vector together with its simulation result.
std::string visualization::build_graph_dot (const ESE::Graph &graph)
Builds a Graphviz dot representation of a generic ESE::Graph.
void plot_span (std::span< const int > values, const char *filename)
Writes a circuit-vector diagram to filename.
void plot_graph (const ESE::Graph &graph, const char *filename)
Writes a ESE::Graph diagram to filename.
void visualization::plot_circuit_diagnostic (std::span< const int > circuit_vector, const char *filename)
Simulates circuit_vector and writes an annotated diagram to filename.
Function Documentation
plot_graph()
void plot_graph (const ESE::Graph & graph, const char * filename)
Writes a ESE::Graph diagram to filename.
Generates DOT source via visualization::build_graph_dot() and persists it using write_or_render(), which will request Graphviz to produce an image when the extension is recognised.
Parameters
graph Graph to visualise.
filename Destination file path (nullptr is a no-op).
Definition at line 428 of file Visualization.cpp.
References visualization::build_graph_dot().
plot_span()
void plot_span (std::span< const int > values, const char * filename)
Writes a circuit-vector diagram to filename.
Generates DOT source via visualization::build_circuit_dot() and persists it using write_or_render(), which will request Graphviz to produce an image when the extension is recognised.
Parameters
values The flat integer circuit vector to visualise.
filename Destination file path (nullptr is a no-op).
Definition at line 413 of file Visualization.cpp.
References visualization::build_circuit_dot().
Referenced by cli::OptimiseExecutor::Execute().