Palusznium Rush: CSimulator Class Reference
CSimulator Class Reference
Circuit mass-balance simulator.
#include <CSimulator.h>
Public Member Functions
CSimulator ()=default
Construct a simulator with default numerical options.
CSimulator (mass_balance::SSimulationOptions options)
Construct a simulator with explicit numerical options.
mass_balance::SSimulationResult Simulate (std::span< const int > circuit_span) const
Simulate the steady-state mass balance of an encoded circuit.
double EvaluatePerformance (std::span< const int > circuit_span) const
Evaluate a circuit as a scalar GA fitness value.
Detailed Description
Circuit mass-balance simulator.
This class is intentionally stateless apart from numerical options. A fresh instance can be created cheaply wherever a circuit needs to be evaluated.
Definition at line 163 of file CSimulator.h.
Constructor & Destructor Documentation
CSimulator() [1/2]
CSimulator::CSimulator () default
Construct a simulator with default numerical options.
CSimulator() [2/2]
CSimulator::CSimulator (mass_balance::SSimulationOptions options) explicit
Construct a simulator with explicit numerical options.
Parameters
options Convergence tolerance, iteration limit, numerical guards, and failure penalty.
Definition at line 351 of file CSimulator.cpp.
Member Function Documentation
EvaluatePerformance()
double CSimulator::EvaluatePerformance (std::span< const int > circuit_span) const nodiscard
Evaluate a circuit as a scalar GA fitness value.
Parameters
circuit_span Full encoded circuit vector.
Returns
Economic value in pounds per second, or a large negative penalty if the circuit is malformed or fails to converge.
Definition at line 462 of file CSimulator.cpp.
References mass_balance::SSimulationResult::converged, Simulate(), mass_balance::SSimulationResult::valid_shape, and mass_balance::SSimulationResult::value_per_s.
Referenced by circuit_performance().
Simulate()
mass_balance::SSimulationResult CSimulator::Simulate (std::span< const int > circuit_span) const nodiscard
Simulate the steady-state mass balance of an encoded circuit.
Parameters
circuit_span Full circuit vector using the agreed GATypedefs.h encoding.
Returns
Diagnostic simulation result containing final product streams, convergence information, mass residual, and economic value.
The method uses successive substitution. Each iteration computes every unit output from the previous unit-feed estimate, resets all unit feeds/products, injects the external feed, routes every unit output according to the circuit vector, and checks the relative change in unit feeds.
Definition at line 353 of file CSimulator.cpp.
References mass_balance::SSimulationResult::converged, cv_feed_dest(), cv_has_valid_shape(), cv_num_units(), cv_unit_dest(), cv_unit_type(), CEconomicModel::Evaluate(), mass_balance::SSimulationResult::failure_reason, mass_balance::SSimulationResult::iterations, mass_balance::SSimulationResult::mass_residual_kg_per_s, mass_balance::SSimulationResult::max_relative_change, mass_balance::SSimulationResult::products, mass_balance::SSimulationResult::valid_shape, and mass_balance::SSimulationResult::value_per_s.
Referenced by EvaluatePerformance().
The documentation for this class was generated from the following files:
CSimulator.h
CSimulator.cpp