Palusznium Rush: CEconomicModel Class Reference
CEconomicModel Class Reference
Stateless economic model for scoring circuit product streams.
#include <CEconomicModel.h>
Public Member Functions
CEconomicModel ()=default
Construct the base-case economic model.
CEconomicModel (SEconomicParameters parameters)
Construct an economic model with explicit parameters.
double Evaluate (std::span< const int > circuit_span, const mass_balance::SProductStreams &products) const
Compute economic value from final products and encoded unit types.
Detailed Description
Stateless economic model for scoring circuit product streams.
Definition at line 48 of file CEconomicModel.h.
Constructor & Destructor Documentation
CEconomicModel() [1/2]
CEconomicModel::CEconomicModel () default
Construct the base-case economic model.
CEconomicModel() [2/2]
CEconomicModel::CEconomicModel (SEconomicParameters parameters) explicit
Construct an economic model with explicit parameters.
Parameters
parameters Product values, product penalties, and unit operating costs.
Definition at line 20 of file CEconomicModel.cpp.
Member Function Documentation
Evaluate()
double CEconomicModel::Evaluate (std::span< const int > circuit_span, const mass_balance::SProductStreams & products) const nodiscard
Compute economic value from final products and encoded unit types.
Parameters
circuit_span Full encoded circuit vector. This is used only to count type A and type B units for operating-cost penalties.
products Final outlet streams from a converged mass-balance simulation.
Returns
Economic value in pounds per second.
Definition at line 22 of file CEconomicModel.cpp.
References mass_balance::SStream::component_kg_per_s, cv_num_units(), cv_unit_type(), mass_balance::SProductStreams::gormanium_product, mass_balance::kGormanium, mass_balance::kPalusznium, mass_balance::kWaste, and mass_balance::SProductStreams::palusznium_product.
Referenced by CSimulator::Simulate().
The documentation for this class was generated from the following files:
CEconomicModel.h
CEconomicModel.cpp