Palusznium Rush: DefaultRandomNumberGenerator Class Reference
DefaultRandomNumberGenerator Class Reference
#include <PRNG.h>
Public Member Functions
DefaultRandomNumberGenerator ()
DefaultRandomNumberGenerator (unsigned)
DefaultRandomNumberGenerator (std::seed_seq &seq)
int rand (int min, int max) override
double random (double min, double max) override
Public Member Functions inherited from RandomNumberGenerator
RandomNumberGenerator ()=default
virtual ~RandomNumberGenerator ()=default
Protected Member Functions
int lcg_rand ()
Static Protected Attributes
static std::uint64_t global_seed = 0
Static Protected Attributes inherited from RandomNumberGenerator
static int RNG_DEFAULT_MIN = 0
static int RNG_MAX = 32767
Friends
void seed_rngs (unsigned seed)
Detailed Description
Definition at line 10 of file PRNG.h.
Constructor & Destructor Documentation
DefaultRandomNumberGenerator() [1/3]
DefaultRandomNumberGenerator::DefaultRandomNumberGenerator ()
Definition at line 19 of file PRNG.cpp.
References global_seed.
DefaultRandomNumberGenerator() [2/3]
DefaultRandomNumberGenerator::DefaultRandomNumberGenerator (unsigned seed) explicit
Definition at line 28 of file PRNG.cpp.
DefaultRandomNumberGenerator() [3/3]
DefaultRandomNumberGenerator::DefaultRandomNumberGenerator (std::seed_seq & seq) explicit
Definition at line 33 of file PRNG.cpp.
Member Function Documentation
lcg_rand()
int DefaultRandomNumberGenerator::lcg_rand () protected
Definition at line 40 of file PRNG.cpp.
References RandomNumberGenerator::RNG_MAX.
Referenced by rand(), and random().
rand()
int DefaultRandomNumberGenerator::rand (int min, int max) override virtual
Implements RandomNumberGenerator.
Definition at line 47 of file PRNG.cpp.
References lcg_rand().
random()
double DefaultRandomNumberGenerator::random (double min, double max) override virtual
Implements RandomNumberGenerator.
Definition at line 51 of file PRNG.cpp.
References lcg_rand(), RandomNumberGenerator::RNG_DEFAULT_MIN, and RandomNumberGenerator::RNG_MAX.
Friends And Related Symbol Documentation
seed_rngs
void seed_rngs (unsigned seed) friend
Definition at line 9 of file PRNG.cpp.
References global_seed.
Member Data Documentation
global_seed
std::uint64_t DefaultRandomNumberGenerator::global_seed = 0 static protected
Definition at line 14 of file PRNG.h.
Referenced by DefaultRandomNumberGenerator(), and seed_rngs.
The documentation for this class was generated from the following files:
PRNG.h
PRNG.cpp