Palusznium Rush: cli::OptimiseExecutor Class Reference
cli::OptimiseExecutor Class Reference
Strategy that runs the genetic algorithm and reports the best circuit.
#include <CommandExecutor.h>
Public Member Functions
OptimiseExecutor (std::ostream &result_stream, std::ostream &log_stream)
int Execute (const CliOptions &options) override
Execute the mode using the supplied options.
Public Member Functions inherited from cli::IModeExecutor
virtual ~IModeExecutor ()=default
Additional Inherited Members
Protected Member Functions inherited from cli::IModeExecutor
IModeExecutor (std::ostream &result_stream, std::ostream &log_stream)
Protected Attributes inherited from cli::IModeExecutor
std::ostream & result_stream_
std::ostream & log_stream_
Detailed Description
Strategy that runs the genetic algorithm and reports the best circuit.
Definition at line 43 of file CommandExecutor.h.
Constructor & Destructor Documentation
OptimiseExecutor()
cli::OptimiseExecutor::OptimiseExecutor (std::ostream & result_stream, std::ostream & log_stream)
Definition at line 370 of file CommandExecutor.cpp.
References cli::IModeExecutor::IModeExecutor().
Member Function Documentation
Execute()
int cli::OptimiseExecutor::Execute (const CliOptions & options) nodiscard override virtual
Execute the mode using the supplied options.
Parameters
options Fully validated options from CliParser::Parse.
Returns
Process exit code. Zero on success.
Implements cli::IModeExecutor.
Definition at line 375 of file CommandExecutor.cpp.
References cli::CliOptions::case_preset, check_validity(), cli::CliOptions::circuit, cv_variable_length(), BaseResult< T >::data, cli::CliOptions::economic, CSimulator::EvaluatePerformance(), cli::CircuitInputs::fixed_prefix, cli::CliOptions::ga, cli::IModeExecutor::log_stream_, cli::CliOptions::method, optimize_span(), optimize_span_sa(), optimize_swappable_span(), optimize_swappable_span_sa(), cli::CliOptions::outputs, BaseResult< T >::performance, cli::OutputPaths::plot_image, plot_span(), cli::IModeExecutor::result_stream_, cli::GaOverrides::rng_seed, cli::CliOptions::sa, seed_rngs(), cli::SimulatedAnnealing, cli::Swappable, unit_block_crossover(), GA_Functions::vector_crossover, and GA_Functions::vector_extent.
The documentation for this class was generated from the following files:
CommandExecutor.h
CommandExecutor.cpp