Palusznium Rush: RandomNumberGenerator Class Reference
RandomNumberGenerator Class Reference abstract
#include <RequiredFunctions.h>
Public Member Functions
RandomNumberGenerator ()=default
virtual ~RandomNumberGenerator ()=default
virtual int rand (int min=RNG_DEFAULT_MIN, int max=RNG_MAX)=0
virtual double random (double min=0.0, double max=1.0)=0
Static Protected Attributes
static int RNG_DEFAULT_MIN = 0
static int RNG_MAX = 32767
Detailed Description
Definition at line 19 of file RequiredFunctions.h.
Constructor & Destructor Documentation
RandomNumberGenerator()
RandomNumberGenerator::RandomNumberGenerator () default
~RandomNumberGenerator()
virtual RandomNumberGenerator::~RandomNumberGenerator () virtual default
Member Function Documentation
rand()
virtual int RandomNumberGenerator::rand (int min = RNG_DEFAULT_MIN, int max = RNG_MAX) pure virtual
Implemented in DefaultRandomNumberGenerator.
References RNG_DEFAULT_MIN, and RNG_MAX.
Referenced by default_crossover(), default_generator(), and default_mutator().
random()
virtual double RandomNumberGenerator::random (double min = 0.0, double max = 1.0) pure virtual
Implemented in DefaultRandomNumberGenerator.
Member Data Documentation
RNG_DEFAULT_MIN
int RandomNumberGenerator::RNG_DEFAULT_MIN = 0 static protected
Definition at line 22 of file RequiredFunctions.h.
Referenced by rand(), and DefaultRandomNumberGenerator::random().
RNG_MAX
int RandomNumberGenerator::RNG_MAX = 32767 static protected
Definition at line 23 of file RequiredFunctions.h.
Referenced by DefaultRandomNumberGenerator::lcg_rand(), rand(), and DefaultRandomNumberGenerator::random().
The documentation for this class was generated from the following files:
RequiredFunctions.h
PRNG.cpp