Palusznium Rush: circuit_vector Namespace Reference
circuit_vector Namespace Reference
Classes
struct CircuitUnitSpec
struct CircuitSpec
struct ParseResult
Enumerations
enum class DestinationKind {
Unit , GormaniumProduct , PaluszniumProduct , Tailings ,
Invalid
}
Functions
DestinationKind destination_kind (int destination, int n_units)
Classifies an output destination integer relative to a circuit of n_units units.
bool is_unit_destination (int destination, int n_units)
Returns true if destination is referring to a separation unit.
bool is_outlet_destination (int destination, int n_units)
Returns true if destination refers to a final outlet stream.
std::string destination_name (int destination, int n_units)
Returns a user-readable label for a destination value.
ParseResult parse_circuit_vector (std::span< const int > circuit_vector)
Parses a flat integer circuit vector into a structured ParseResult.
std::vector< int > encode_circuit_vector (const CircuitSpec &spec)
Encodes a CircuitSpec back into a flat integer circuit vector.
Enumeration Type Documentation
DestinationKind
enum class circuit_vector::DestinationKind strong
Enumerator
Unit
GormaniumProduct
PaluszniumProduct
Tailings
Invalid
Definition at line 24 of file CircuitVectorParser.h.
Function Documentation
destination_kind()
DestinationKind circuit_vector::destination_kind (int destination, int n_units)
Classifies an output destination integer relative to a circuit of n_units units.
The circuit encoding indicates and reserves destinations as shown below:
n_units: Palusznium product outlet (DestinationKind::Palusz)
n_units + 1: Gormanium product outlet (DestinationKind::Gorman)
n_units + 2: Tailings outlet (DestinationKind::Tailings)
otherwise: DestinationKind::Invalid
Parameters
destination Raw destination value read from a circuit vector.
n_units Total numer of separation units in the circuit (which must be larger than zero).
Returns
DestinationKind corresponding to where the destination maps to.
Definition at line 26 of file CircuitVectorParser.cpp.
References GormaniumProduct, Invalid, PaluszniumProduct, Tailings, and Unit.
Referenced by destination_name(), is_outlet_destination(), is_unit_destination(), and parse_circuit_vector().
destination_name()
std::string circuit_vector::destination_name (int destination, int n_units)
Returns a user-readable label for a destination value.
This is intended for user-friendly messages and visualisation captions.
Parameters
destination The raw destination value from a circuit vector.
n_units Total number of separation units in the circuit.
Returns
A string identifying the destination.
Definition at line 85 of file CircuitVectorParser.cpp.
References destination_kind(), GormaniumProduct, Invalid, PaluszniumProduct, Tailings, and Unit.
encode_circuit_vector()
std::vector< int > circuit_vector::encode_circuit_vector (const CircuitSpec & spec)
Encodes a CircuitSpec back into a flat integer circuit vector.
This is the inverse of parse_circuit_vector(). The user is responsible for ensuring that spec is internally consistent, such that spec.n_units == spec.units.size().
Parameters
spec A fully populated CircuitSpec, which will be obtained from a successful parse_circuit_vector() call or built via a program.
Returns
The flat integer vector encoding spec.
Definition at line 213 of file CircuitVectorParser.cpp.
References circuit_vector::CircuitSpec::feed_destination, circuit_vector::CircuitSpec::n_inputs, circuit_vector::CircuitSpec::n_product_streams, circuit_vector::CircuitSpec::n_units, and circuit_vector::CircuitSpec::units.
Referenced by circuit_graph::graph_to_circuit_vector().
is_outlet_destination()
bool circuit_vector::is_outlet_destination (int destination, int n_units)
Returns true if destination refers to a final outlet stream.
Final outlets are defined as the Palusznium product, Gormanium product, and Tailings streams. Anything else is either not a unit-to-unit routing, or an invalid value.
Parameters
destination The raw destination value from a circuit vector.
n_units Total number of separation units in the circuit.
Returns
true when destination is one of the three defined outlets, false otherwise.
Definition at line 69 of file CircuitVectorParser.cpp.
References destination_kind(), GormaniumProduct, PaluszniumProduct, and Tailings.
is_unit_destination()
bool circuit_vector::is_unit_destination (int destination, int n_units)
Returns true if destination is referring to a separation unit.
This logic is equivalent to checking whether destination_kind() returns DestinationKind::Unit.
Parameters
destination Raw destination value from a circuit vector.
n_units Total number of separation units in the circuit.
Returns
true when the destination is a valid unit index false otherwise.
Definition at line 52 of file CircuitVectorParser.cpp.
References destination_kind(), and Unit.
Referenced by parse_circuit_vector().
parse_circuit_vector()
ParseResult circuit_vector::parse_circuit_vector (std::span< const int > circuit_vector)
Parses a flat integer circuit vector into a structured ParseResult.
There are several constraints enforced, such as:
exactly one feed input (n_inputs == 1).
at least one unit (n_units > 0).
exactly three product streams (n_product_streams == 3).
each unit has either 2 (Type A) or 3 (Type B) outputs.
the feed must route to a unit, and not directly to an outlet.
all destination values must be in the valid range between 0 and n_units + 2.
the total vector lenght must match exactly with the declared structure.
Parameters
circuit_vector The flat integer encoding of the circuit.
Returns
A ParseResult describing the outcome of the parse.
Definition at line 117 of file CircuitVectorParser.cpp.
References destination_kind(), circuit_vector::CircuitUnitSpec::destinations, circuit_vector::ParseResult::error, circuit_vector::CircuitSpec::feed_destination, circuit_vector::CircuitUnitSpec::id, Invalid, is_unit_destination(), circuit_vector::CircuitSpec::n_inputs, circuit_vector::CircuitSpec::n_product_streams, circuit_vector::CircuitSpec::n_units, circuit_vector::ParseResult::ok, circuit_vector::CircuitUnitSpec::output_count, circuit_vector::ParseResult::spec, and circuit_vector::CircuitSpec::units.
Referenced by visualization::build_circuit_dot(), visualization::build_circuit_dot(), circuit_graph::circuit_vector_to_csr_graph(), circuit_graph::graph_to_circuit_vector(), and vector_check_validity().