Palusznium Rush: circuit_graph Namespace Reference
circuit_graph Namespace Reference
Functions
ESE::CSRGraph circuit_vector_to_csr_graph (std::span< const int > circuit_span)
Convert an encoded circuit vector into an ESE CSR graph.
std::vector< int > graph_to_circuit_vector (const ESE::Graph &graph)
Convert an ESE graph back into the encoded circuit-vector format.
Function Documentation
circuit_vector_to_csr_graph()
ESE::CSRGraph circuit_graph::circuit_vector_to_csr_graph (std::span< const int > circuit_span) nodiscard
Convert an encoded circuit vector into an ESE CSR graph.
Parameters
circuit_span Encoded circuit vector in the agreed project format.
Returns
CSR graph with one root node, n dynamic unit nodes, and three sink nodes.
Exceptions
std::invalid_argument if the circuit vector cannot be parsed.
The CSR input-index layout expected by ESEGraph is: [root targets..., dynamic node output targets...]. For this project there is exactly one root target: the circuit feed destination.
Destination numbering is preserved exactly:
0 ... n_units - 1 are unit nodes;
n_units is the palusznium product sink;
n_units + 1 is the gormanium product sink;
n_units + 2 is the tailings sink.
Definition at line 49 of file CircuitGraphConverter.cpp.
References circuit_vector::CircuitUnitSpec::destinations, circuit_vector::ParseResult::error, circuit_vector::CircuitSpec::feed_destination, circuit_vector::CircuitSpec::n_inputs, circuit_vector::CircuitSpec::n_product_streams, circuit_vector::CircuitSpec::n_units, circuit_vector::ParseResult::ok, circuit_vector::CircuitUnitSpec::output_count, circuit_vector::parse_circuit_vector(), circuit_vector::ParseResult::spec, and circuit_vector::CircuitSpec::units.
graph_to_circuit_vector()
std::vector< int > circuit_graph::graph_to_circuit_vector (const ESE::Graph & graph) nodiscard
Convert an ESE graph back into the encoded circuit-vector format.
Parameters
graph ESE graph whose root/dynamic/sink layout follows the project convention.
Returns
Encoded circuit vector.
Exceptions
std::invalid_argument if the graph does not have the project circuit shape.
The output count of each dynamic node becomes the unit type in the vector: degree 2 is type A and degree 3 is type B. The first root edge becomes the circuit-feed destination. The order of each dynamic node's outgoing targets is preserved.
Definition at line 83 of file CircuitGraphConverter.cpp.
References circuit_vector::CircuitUnitSpec::destinations, circuit_vector::encode_circuit_vector(), circuit_vector::ParseResult::error, circuit_vector::CircuitSpec::feed_destination, circuit_vector::CircuitUnitSpec::id, circuit_vector::CircuitSpec::n_inputs, circuit_vector::CircuitSpec::n_product_streams, circuit_vector::CircuitSpec::n_units, circuit_vector::ParseResult::ok, circuit_vector::CircuitUnitSpec::output_count, circuit_vector::parse_circuit_vector(), and circuit_vector::CircuitSpec::units.
Referenced by circuit_performance().