Palusznium Rush: visualization Namespace Reference
visualization Namespace Reference
Functions
std::string build_circuit_dot (std::span< const int > circuit_vector)
Builds a Graphviz dot representation of a circuit vector.
std::string build_circuit_dot (std::span< const int > circuit_vector, const mass_balance::SSimulationResult &result)
Builds an annotated Graphviz dot representation of a circuit vector together with its simulation result.
std::string graphviz_output_format (const char *filename)
Returns the Graphviz output format string provided by filename's extension.
std::string build_graph_dot (const ESE::Graph &graph)
Builds a Graphviz dot representation of a generic ESE::Graph.
void plot_circuit_diagnostic (std::span< const int > circuit_vector, const char *filename)
Simulates circuit_vector and writes an annotated diagram to filename.
Function Documentation
build_circuit_dot() [1/2]
std::string visualization::build_circuit_dot (std::span< const int > circuit_vector)
Builds a Graphviz dot representation of a circuit vector.
Generates a directed graph showing all separation units and connections to the feed, the Palusznium concentrate, the Gormanium concentrate, and the Tailings outlet.
Edge colours follow the convention:
blue = first concentrate output (slot 0).
green = second concentrate output (slot 1, Type B units only).
red = tailings output (last slot).
If the circuit vector cannot be parsed, the dot source will contain an error node describing the problem. Nevertheless, the graph is still returned as a valid DOT string. The circuit vector is embedded in the diagram's bottom label as well.
Parameters
circuit_vector The flat integer encoding of the circuit to visualise.
Returns
A string containing Graphviz DOT source.
Definition at line 129 of file Visualization.cpp.
References circuit_vector::parse_circuit_vector().
Referenced by plot_circuit_diagnostic(), and plot_span().
build_circuit_dot() [2/2]
std::string visualization::build_circuit_dot (std::span< const int > circuit_vector, const mass_balance::SSimulationResult & result)
Builds an annotated Graphviz dot representation of a circuit vector together with its simulation result.
Extends beyond the build_circuit_dot() output with:
an economic caption (value, Palusznium recovery, and grade) which is provided by result, or an error/non-convergence message when appropriate.
filled node colours for product and tailings sinks (green for Palusznium, light grey for Gormanium and Tailings).
unit-type label ([A] or [B]) on each unit node.
embedded legend sub-graph explaining edge colours.
Edge colours use the same convention as the general overload:
blue = first concentrate output.
green = second concentrate output (Type B units only).
red = tailings output.
Parameters
circuit_vector The flat integer encoding of the circuit to visualise.
result The simulation result from CSimulator::Simulate().
Returns
A string containing Graphviz DOT source.
Definition at line 215 of file Visualization.cpp.
References circuit_vector::parse_circuit_vector().
build_graph_dot()
std::string visualization::build_graph_dot (const ESE::Graph & graph)
Builds a Graphviz dot representation of a generic ESE::Graph.
Renders the graph as a diagram with three classes of nodes:
root nodes (feeds), labelled "feed" or "feed N" for multiple feeds.
dynamic nodes (separation units), labelled by their zero index.
sink nodes (outlets), labelled "exit N".
All edges from root and dynamic nodes are drawn without colour annotation, in order to enable for a generic graph representation rather than a circuit-specific visualisation.
Parameters
graph The ESE::Graph to visualise.
Returns
A string containing Graphviz DOT source.
Definition at line 308 of file Visualization.cpp.
Referenced by plot_graph().
graphviz_output_format()
std::string visualization::graphviz_output_format (const char * filename)
Returns the Graphviz output format string provided by filename's extension.
Is readily capable of recognising .png, .svg, and .pdf (case-insensitive). The string that is returned can be passed to the -T flag of the dot command-line tool. An empty string is returned for unrecognised or missing extensions, such that the user is must write raw DOT text instead.
Parameters
filename An output file path or nullptr.
Returns
"png", "svg", "pdf", or "" if format is unknown.
Definition at line 100 of file Visualization.cpp.
plot_circuit_diagnostic()
void visualization::plot_circuit_diagnostic (std::span< const int > circuit_vector, const char * filename)
Simulates circuit_vector and writes an annotated diagram to filename.
Runs a full mass balance simulation via CSimulator::Simulate(), then proceeds to build an annotated DOT diagram using two argument overload of build_circuit_dot(). This includes the economic caption, node-type labels, coloured outlet nodes, and an embedded legend. The result is persisted by write_or_render().
Parameters
circuit_vector The flat integer circuit vector to simulate and visualise.
filename Destination file path (nullptr is a no-op).
Definition at line 449 of file Visualization.cpp.
References build_circuit_dot(), and CSimulator::Simulate().
Referenced by cli::VisualiseExecutor::Execute().