Palusznium Rush: GA_Functions Struct Reference
GA_Functions Struct Reference
#include <RequiredFunctions.h>
Public Attributes
std::size_t(* vector_extent)(std::span< const int > const fixed_prefix)
void(* vector_generator)(std::span< const int > const fixed_prefix, std::span< int > values, RandomNumberGenerator &rng) = &default_generator
void(* vector_mutator)(std::span< const int > const fixed_prefix, std::span< int > values, std::size_t max_mutations, RandomNumberGenerator &rng) = &default_mutator
void(* vector_crossover)(std::span< const int > const fixed_prefix, std::span< const int > const parent1_values, std::span< const int > const parent2_values, std::span< std::span< int > > child_values, RandomNumberGenerator &rng) = &default_crossover
double(* vector_similarity)(std::span< const int > const fixed_prefix, std::span< const int > const vec1, std::span< const int > const vec2) = &default_similarity
Detailed Description
Definition at line 55 of file RequiredFunctions.h.
Member Data Documentation
vector_crossover
void(* GA_Functions::vector_crossover) (std::span< const int > const fixed_prefix, std::span< const int > const parent1_values, std::span< const int > const parent2_values, std::span< std::span< int > > child_values, RandomNumberGenerator &rng) = &default_crossover
Definition at line 67 of file RequiredFunctions.h.
Referenced by cli::OptimiseExecutor::Execute().
vector_extent
std::size_t(* GA_Functions::vector_extent) (std::span< const int > const fixed_prefix)
Definition at line 58 of file RequiredFunctions.h.
Referenced by cli::OptimiseExecutor::Execute(), optimize_span(), optimize_span_sa(), and optimize_swappable_span_sa().
vector_generator
void(* GA_Functions::vector_generator) (std::span< const int > const fixed_prefix, std::span< int > values, RandomNumberGenerator &rng) = &default_generator
Definition at line 60 of file RequiredFunctions.h.
Referenced by optimize_span(), and optimize_swappable_span_sa().
vector_mutator
void(* GA_Functions::vector_mutator) (std::span< const int > const fixed_prefix, std::span< int > values, std::size_t max_mutations, RandomNumberGenerator &rng) = &default_mutator
Definition at line 63 of file RequiredFunctions.h.
Referenced by optimize_span_sa(), and optimize_swappable_span_sa().
vector_similarity
double(* GA_Functions::vector_similarity) (std::span< const int > const fixed_prefix, std::span< const int > const vec1, std::span< const int > const vec2) = &default_similarity
Definition at line 73 of file RequiredFunctions.h.
The documentation for this struct was generated from the following file:
RequiredFunctions.h